"""Initial Migration

Revision ID: 6fa7082a5069
Revises: 
Create Date: 2024-09-23 11:59:52.583190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa7082a5069'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('bankaccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_details', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bankitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_details', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashbookdebits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=False),
    sa.Column('bank', sa.String(), nullable=True),
    sa.Column('bank_amount', sa.Float(), nullable=True),
    sa.Column('cash_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=False),
    sa.Column('bank', sa.String(), nullable=True),
    sa.Column('bank_amount', sa.Float(), nullable=True),
    sa.Column('cash_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_type', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(length=80), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(length=80), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=80), nullable=True),
    sa.Column('kra_pin', sa.String(length=80), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('payment_terms', sa.String(length=80), nullable=True),
    sa.Column('total_amount_owed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_email'),
    sa.UniqueConstraint('customer_phone')
    )
    op.create_table('deliverynotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('delivery_number', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('vendor_pin', sa.String(), nullable=True),
    sa.Column('origin_place', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('driver_contact', sa.String(), nullable=True),
    sa.Column('driver', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('deposit_from', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('bank_charges', sa.String(), nullable=True),
    sa.Column('bank_details', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_name', sa.String(), nullable=False),
    sa.Column('expense_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paymentsmade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment', sa.Integer(), nullable=True),
    sa.Column('payment_amount', sa.Integer(), nullable=False),
    sa.Column('payment_mode', sa.String(), nullable=False),
    sa.Column('payment_date', sa.String(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('vendor_phone', sa.String(), nullable=True),
    sa.Column('vendor_email', sa.String(), nullable=True),
    sa.Column('vendor_pin', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_details', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('deposit_to', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pumpnames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pump_name', sa.String(), nullable=True),
    sa.Column('pump_location', sa.String(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('litres', sa.Integer(), nullable=True),
    sa.Column('initial_reading', sa.Integer(), nullable=True),
    sa.Column('reading', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('vat', sa.String(), nullable=True),
    sa.Column('supplier_name', sa.String(), nullable=True),
    sa.Column('supplier_pin', sa.String(), nullable=True),
    sa.Column('credit', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('terms', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retreadedtyres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('starting_mileage', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('final_mileage', sa.Integer(), nullable=True),
    sa.Column('tyre_mileage', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retreadtyres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tyre_mileage', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retreadtyretrips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('vendor_phone', sa.String(), nullable=True),
    sa.Column('vendor_email', sa.String(), nullable=True),
    sa.Column('vendor_pin', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('trip_number', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retreadtyreupdates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('shopretreads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('tyre_mileage', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sparecategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spare_category_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('measurement', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactionsreceived',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('customer_pin', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('amount_received', sa.Float(), nullable=False),
    sa.Column('bank_details', sa.String(), nullable=True),
    sa.Column('bank_charges', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.String(length=80), nullable=False),
    sa.Column('payment', sa.Float(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('payment_mode', sa.String(length=80), nullable=False),
    sa.Column('deposit_to', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_number', sa.String(), nullable=False),
    sa.Column('driver', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('trailer', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('truck_number')
    )
    op.create_table('tyres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unfitremoveretreadtyres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('starting_mileage', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('final_mileage', sa.Integer(), nullable=True),
    sa.Column('tyre_mileage', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('vendor_email', sa.String(), nullable=False),
    sa.Column('vendor_phone', sa.String(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=True),
    sa.Column('kra_pin', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('total_amount_owed', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_email'),
    sa.UniqueConstraint('vendor_phone')
    )
    op.create_table('account_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balancesheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliverynoteitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliverynote_id', sa.Integer(), nullable=False),
    sa.Column('container_number', sa.String(), nullable=True),
    sa.Column('cargo_description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('measurement', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deliverynote_id'], ['deliverynotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oldtyres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('starting_mileage', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('retread_counter', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('final_mileage', sa.Integer(), nullable=True),
    sa.Column('tyre_mileage', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('pumpfuelings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('pump_location', sa.String(), nullable=True),
    sa.Column('pump_name', sa.String(), nullable=True),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('litres', sa.Integer(), nullable=True),
    sa.Column('reading', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('order', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pump_id'], ['pumpnames.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pumpupdates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pump_id', sa.Integer(), nullable=False),
    sa.Column('pump_name', sa.String(), nullable=True),
    sa.Column('litres', sa.Integer(), nullable=True),
    sa.Column('reading', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pump_id'], ['pumpnames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('quote_number', sa.Integer(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('vendor_pin', sa.String(), nullable=True),
    sa.Column('type_vat', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number')
    )
    op.create_table('removeretreadtyres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('starting_mileage', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('removetyres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('starting_mileage', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('retreadtyretripitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('tyre_mileage', sa.Float(), nullable=True),
    sa.Column('status', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['retreadtyretrips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sparesubcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spare_subcategory_id', sa.Integer(), nullable=True),
    sa.Column('spare_subcategory_name', sa.String(), nullable=True),
    sa.Column('spare_category_name', sa.String(), nullable=True),
    sa.Column('measurement', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['spare_subcategory_id'], ['sparecategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=True),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('mechanic', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('spare_category', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_profit_loss_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiclemantainances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('truck_number', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('job_description', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('repair_number', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creditnotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('credit_number', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('credit_date', sa.String(), nullable=True),
    sa.Column('type_vat', sa.String(), nullable=True),
    sa.Column('vendor_pin', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['account_categories.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_number')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('vendor_pin', sa.String(), nullable=True),
    sa.Column('type_vat', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('amount_owed', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('consignee', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.String(), nullable=False),
    sa.Column('invoice_terms', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=False),
    sa.Column('sales_person', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['account_categories.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('newbills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('vendor_phone', sa.String(), nullable=True),
    sa.Column('vendor_email', sa.String(), nullable=True),
    sa.Column('bill_number', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('bill_date', sa.String(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('type_vat', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('vendor_pin', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('amount_owed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['account_categories.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_number')
    )
    op.create_table('quoteitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('vat', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('rate_vat', sa.Integer(), nullable=True),
    sa.Column('sub_total', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiclemantainaceitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('mantainace_id', sa.Integer(), nullable=False),
    sa.Column('spare_subcategory_name', sa.String(), nullable=True),
    sa.Column('spare_category_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('mechanic', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mantainace_id'], ['vehiclemantainances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creditnotesitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('sub_total', sa.Float(), nullable=True),
    sa.Column('vat', sa.Integer(), nullable=False),
    sa.Column('rate_vat', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('measurement', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['creditnotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoiceitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('vat', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('rate_vat', sa.Float(), nullable=True),
    sa.Column('sub_total', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newbillitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('item_details', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('sub_total', sa.Float(), nullable=True),
    sa.Column('vat', sa.Integer(), nullable=False),
    sa.Column('rate_vat', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('spare_name', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tyre_mileage', sa.String(), nullable=True),
    sa.Column('measurement', sa.String(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['newbills.id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newbillitems')
    op.drop_table('invoiceitems')
    op.drop_table('creditnotesitems')
    op.drop_table('vehiclemantainaceitems')
    op.drop_table('quoteitems')
    op.drop_table('newbills')
    op.drop_table('invoices')
    op.drop_table('creditnotes')
    op.drop_table('vehiclemantainances')
    op.drop_table('trading_profit_loss_accounts')
    op.drop_table('stores')
    op.drop_table('sparesubcategories')
    op.drop_table('retreadtyretripitems')
    op.drop_table('removetyres')
    op.drop_table('removeretreadtyres')
    op.drop_table('quotes')
    op.drop_table('pumpupdates')
    op.drop_table('pumpfuelings')
    op.drop_table('oldtyres')
    op.drop_table('deliverynoteitems')
    op.drop_table('balancesheets')
    op.drop_table('account_categories')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('updates')
    op.drop_table('unfitremoveretreadtyres')
    op.drop_table('tyres')
    op.drop_table('trucks')
    op.drop_table('transactionsreceived')
    op.drop_table('totals')
    op.drop_table('stockitems')
    op.drop_table('sparecategories')
    op.drop_table('shopretreads')
    op.drop_table('retreadtyreupdates')
    op.drop_table('retreadtyretrips')
    op.drop_table('retreadtyres')
    op.drop_table('retreadedtyres')
    op.drop_table('purchases')
    op.drop_table('pumpnames')
    op.drop_table('paymentsmade')
    op.drop_table('items')
    op.drop_table('funds')
    op.drop_table('expenses')
    op.drop_table('deposits')
    op.drop_table('deliverynotes')
    op.drop_table('customers')
    op.drop_table('cashbooks')
    op.drop_table('cashbookdebits')
    op.drop_table('bankitems')
    op.drop_table('bankaccounts')
    op.drop_table('account_types')
    # ### end Alembic commands ###
